## docker-compose.yml
#version: "3.9"
#services:
#  history-service:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#  db:
#    image: postgres
#    environment:
#      POSTGRES_PASSWORD: example


# docker-compose.yml
version: "3.9"
services:
  history-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PG_DATA: /data/postgres
    volumes:
      - ./postgres-data:/data/postgres # comment if no need to persist data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"